/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Help: typeof import('./src/components/Help.vue')['default']
    RightClick: typeof import('./src/components/RightClick.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    StyleSetting: typeof import('./src/components/StyleSetting.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
