/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Config: typeof import('./src/components/Config/index.vue')['default']
    ConfigDraw: typeof import('./src/components/configDraw.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHelp: typeof import('./src/components/TheHelp.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
